version: '3.7'
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "hyperf"
    networks:
      - net
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.github/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"
  redis:
    image: "redis"
    command:
      - "redis-server"
      - "--databases 256"
    networks:
      - net
    volumes:
      - redis-data:/data
    restart: "always"
  fs-server:
    image: "kydever/fs-server:latest"
    build:
      context: "."
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: "${APP_ENV:-prod}"
      DB_HOST: "mysql"
      REDIS_HOST: "redis"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 8
  fs-frontend:
    image: "kydever/fs-frontend:latest"
    build:
      context: "./frontend"
    ports:
      - "10012:80"
    depends_on:
      - "fs-server"
    networks:
      - net
    restart: "always"
networks:
  net:
volumes:
  mysql-data:
  redis-data:
